[tool.poetry]
name = "feedback-telegram-bot"
version = "0.1.0"
description = "A livegram Telegram bot clone with topics support."
authors = ["yshalsager <ysh-alsager@hotmail.com>"]
license = "MIT"
packages = [{include = "feedbackbot"}]

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = {extras = ["rate-limiter"], version = "^20.6"}
sqlalchemy = "^2.0.22"
alembic = "^1.12.0"
regex = "^2023.10.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"
pre-commit = "^3.5.0"
mypy = "^1.6.0"
ipython = "^8.16.0"
rich = "^13.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = ["src"]
ignore_missing_imports = true
disallow_untyped_defs = true
#disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true
disallow_incomplete_defs = true
disallow_untyped_decorators = false
plugins = ["sqlalchemy.ext.mypy.plugin"]

[tool.ruff]  # https://github.com/charliermarsh/ruff
fix = true
ignore-init-module-imports = true
line-length = 100
select = ["A", "B", "BLE", "C4", "C90", "DTZ", "E", "ERA", "F", "G", "I", "INP", "ISC", "N", "NPY", "PGH", "PIE", "PLC", "PLE", "PLR", "PLW", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "S", "SIM", "T10", "T20", "TID", "UP", "W", "YTT"]
ignore = [
    "E501", "PGH001", "RET504", "S101", "D211", "D213",
    "ERA001", # Found commented-out code
    "G004", # Logging statement uses f-string
    "PLR2004", # Magic value used in comparison, consider replacing 3 with a constant variable
    "PLR0913", # Too many arguments to function call (6 > 5)
    "DTZ002", "DTZ005", # The use of `datetime.datetime.now()` without `tz` argument is not allowed"
    "E712",
    "RUF001",  # ambiguous-unicode-character-string	String contains ambiguous {}. Did you mean {}?
    "ISC001"  # formatter complains about it
]
unfixable = [
    "ERA001", "F401", "F841", "T201", "T203",
    "E711", # none-comparison. SQLAlchemy does not support is None apparently.
    "E712", # true-false-comparison. SQLAlchemy does not support it apparently.
]
src = ["src"]
target-version = "py312"
extend-exclude = ["*.pyi"]

[tool.ruff.extend-per-file-ignores]
"*/migrations/*/*.py" = ["N999"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
